name: echo_date

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  echo_date:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Echo current date and time
        run: date
